(cl:defpackage #:%open-asset-import-library
  (:use :cffi)
  (:nicknames #:%assimp #:%ai)
  (:export
           #:a
           #:a-1
           #:a-2
           #:a-3
           #:a-4
           #:ach-format-hint
           #:ai-anim-behaviour
           #:ai-anim-behaviour-constant
           #:ai-anim-behaviour-default
           #:ai-anim-behaviour-linear
           #:ai-anim-behaviour-repeat
           #:ai-animation
           #:ai-apply-post-processing
           #:ai-attach-log-stream
           #:ai-blend-mode
           #:ai-blend-mode-additive
           #:ai-blend-mode-default
           #:ai-bone
           #:ai-bool
           #:ai-camera
           #:ai-color-3d
           #:ai-color-4d
           #:ai-component
           #:ai-component-animations
           #:ai-component-boneweights
           #:ai-component-cameras
           #:ai-component-colors
           #:ai-component-lights
           #:ai-component-materials
           #:ai-component-meshes
           #:ai-component-normals
           #:ai-component-tangents-and-bitangents
           #:ai-component-texcoords
           #:ai-component-textures
           #:ai-create-quaternion-from-matrix
           #:ai-decompose-matrix
           #:ai-default-log-stream
           #:ai-default-log-stream-debugger
           #:ai-default-log-stream-file
           #:ai-default-log-stream-stderr
           #:ai-default-log-stream-stdout
           #:ai-detach-all-log-streams
           #:ai-detach-log-stream
           #:ai-enable-verbose-logging
           #:ai-face
           #:ai-file
           #:ai-file-close-proc
           #:ai-file-flush-proc
           #:ai-file-io
           #:ai-file-open-proc
           #:ai-file-read-proc
           #:ai-file-seek
           #:ai-file-tell-proc
           #:ai-file-write-proc
           #:ai-get-compile-flags
           #:ai-get-error-string
           #:ai-get-extension-list
           #:ai-get-legal-string
           #:ai-get-material-color
           #:ai-get-material-float-array
           #:ai-get-material-integer-array
           #:ai-get-material-property
           #:ai-get-material-string
           #:ai-get-material-texture
           #:ai-get-material-texture-count
           #:ai-get-memory-requirements
           #:ai-get-predefined-log-stream
           #:ai-get-version-major
           #:ai-get-version-minor
           #:ai-get-version-revision
           #:ai-identity-matrix-3
           #:ai-identity-matrix-4
           #:ai-import-file
           #:ai-import-file-ex
           #:ai-import-file-from-memory
           #:ai-is-extension-supported
           #:ai-light
           #:ai-light-source-directional
           #:ai-light-source-point
           #:ai-light-source-spot
           #:ai-light-source-type
           #:ai-light-source-undefined
           #:ai-log-stream
           #:ai-log-stream-callback
           #:ai-material
           #:ai-material-property
           #:ai-matrix-3x-3
           #:ai-matrix-4x-4
           #:ai-memory-info
           #:ai-mesh
           #:ai-multiply-matrix-3
           #:ai-multiply-matrix-4
           #:ai-node
           #:ai-node-anim
           #:ai-origin
           #:ai-origin-cur
           #:ai-origin-end
           #:ai-origin-set
           #:ai-plane
           #:ai-post-process-steps
           #:ai-primitive-type
           #:ai-primitive-type-line
           #:ai-primitive-type-point
           #:ai-primitive-type-polygon
           #:ai-primitive-type-triangle
           #:ai-process-calc-tangent-space
           #:ai-process-find-degenerates
           #:ai-process-find-instances
           #:ai-process-find-invalid-data
           #:ai-process-fix-infacing-normals
           #:ai-process-flip-u-vs
           #:ai-process-flip-winding-order
           #:ai-process-gen-normals
           #:ai-process-gen-smooth-normals
           #:ai-process-gen-uv-coords
           #:ai-process-improve-cache-locality
           #:ai-process-join-identical-vertices
           #:ai-process-limit-bone-weights
           #:ai-process-make-left-handed
           #:ai-process-optimize-graph
           #:ai-process-optimize-meshes
           #:ai-process-pre-transform-vertices
           #:ai-process-remove-component
           #:ai-process-remove-redundant-materials
           #:ai-process-sort-by-p-type
           #:ai-process-split-large-meshes
           #:ai-process-transform-uv-coords
           #:ai-process-triangulate
           #:ai-process-validate-data-structure
           #:ai-property-type-info
           #:ai-pti-buffer
           #:ai-pti-float
           #:ai-pti-integer
           #:ai-pti-string
           #:ai-quat-key
           #:ai-quaternion
           #:ai-ray
           #:ai-release-import
           #:ai-return
           #:ai-return-failure
           #:ai-return-outofmemory
           #:ai-return-success
           #:ai-scene
           #:ai-set-import-property-float
           #:ai-set-import-property-integer
           #:ai-set-import-property-string
           #:ai-shading-mode
           #:ai-shading-mode-blinn
           #:ai-shading-mode-cook-torrance
           #:ai-shading-mode-flat
           #:ai-shading-mode-fresnel
           #:ai-shading-mode-gouraud
           #:ai-shading-mode-minnaert
           #:ai-shading-mode-no-shading
           #:ai-shading-mode-oren-nayar
           #:ai-shading-mode-phong
           #:ai-shading-mode-toon
           #:ai-string
           #:ai-texel
           #:ai-texture
           #:ai-texture-flags
           #:ai-texture-flags-ignore-alpha
           #:ai-texture-flags-invert
           #:ai-texture-flags-use-alpha
           #:ai-texture-map-mode
           #:ai-texture-map-mode-clamp
           #:ai-texture-map-mode-decal
           #:ai-texture-map-mode-mirror
           #:ai-texture-map-mode-wrap
           #:ai-texture-mapping
           #:ai-texture-mapping-box
           #:ai-texture-mapping-cylinder
           #:ai-texture-mapping-other
           #:ai-texture-mapping-plane
           #:ai-texture-mapping-sphere
           #:ai-texture-mapping-uv
           #:ai-texture-op
           #:ai-texture-op-add
           #:ai-texture-op-divide
           #:ai-texture-op-multiply
           #:ai-texture-op-signed-add
           #:ai-texture-op-smooth-add
           #:ai-texture-op-subtract
           #:ai-texture-type
           #:ai-texture-type-ambient
           #:ai-texture-type-diffuse
           #:ai-texture-type-displacement
           #:ai-texture-type-emissive
           #:ai-texture-type-height
           #:ai-texture-type-lightmap
           #:ai-texture-type-none
           #:ai-texture-type-normals
           #:ai-texture-type-opacity
           #:ai-texture-type-reflection
           #:ai-texture-type-shininess
           #:ai-texture-type-specular
           #:ai-texture-type-unknown
           #:ai-transform-vec-by-matrix-3
           #:ai-transform-vec-by-matrix-4
           #:ai-transpose-matrix-3
           #:ai-transpose-matrix-4
           #:ai-user-data
           #:ai-uv-transform
           #:ai-vector-2d
           #:ai-vector-3d
           #:ai-vector-key
           #:ai-vertex-weight
           #:animations
           #:b
           #:b-1
           #:b-2
           #:b-3
           #:b-4
           #:c
           #:c-1
           #:c-2
           #:c-3
           #:c-4
           #:callback
           #:cameras
           #:close-proc
           #:d
           #:d-1
           #:d-2
           #:d-3
           #:d-4
           #:data
           #:dir
           #:file-size-proc
           #:flush-proc
           #:g
           #:length
           #:lights
           #:m-angle-inner-cone
           #:m-angle-outer-cone
           #:m-animations
           #:m-aspect
           #:m-attenuation-constant
           #:m-attenuation-linear
           #:m-attenuation-quadratic
           #:m-bitangents
           #:m-bones
           #:m-cameras
           #:m-channels
           #:m-children
           #:m-clip-plane-far
           #:m-clip-plane-near
           #:m-color-ambient
           #:m-color-diffuse
           #:m-color-specular
           #:m-colors
           #:m-data
           #:m-data-length
           #:m-direction
           #:m-duration
           #:m-faces
           #:m-flags
           #:m-height
           #:m-horizontal-fov
           #:m-index
           #:m-indices
           #:m-key
           #:m-lights
           #:m-look-at
           #:m-material-index
           #:m-materials
           #:m-meshes
           #:m-name
           #:m-node-name
           #:m-normals
           #:m-num-allocated
           #:m-num-animations
           #:m-num-bones
           #:m-num-cameras
           #:m-num-channels
           #:m-num-children
           #:m-num-faces
           #:m-num-indices
           #:m-num-lights
           #:m-num-materials
           #:m-num-meshes
           #:m-num-position-keys
           #:m-num-properties
           #:m-num-rotation-keys
           #:m-num-scaling-keys
           #:m-num-textures
           #:m-num-uv-components
           #:m-num-vertices
           #:m-num-weights
           #:m-offset-matrix
           #:m-parent
           #:m-position
           #:m-position-keys
           #:m-post-state
           #:m-pre-state
           #:m-primitive-types
           #:m-properties
           #:m-root-node
           #:m-rotation
           #:m-rotation-keys
           #:m-scaling
           #:m-scaling-keys
           #:m-semantic
           #:m-tangents
           #:m-texture-coords
           #:m-textures
           #:m-ticks-per-second
           #:m-time
           #:m-transformation
           #:m-translation
           #:m-type
           #:m-up
           #:m-value
           #:m-vertex-id
           #:m-vertices
           #:m-weight
           #:m-weights
           #:m-width
           #:materials
           #:meshes
           #:nodes
           #:open-proc
           #:pc-data
           #:pos
           #:r
           #:read-proc
           #:seek-proc
           #:size-t
           #:tell-proc
           #:textures
           #:total
           #:user
           #:user-data
           #:w
           #:write-proc
           #:x
           #:y
           #:z))

